bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Martin Proks
  description: MARS-seq v2 preprocessing pipeline
  force: false
  is_nfcore: true
  name: marsseq
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.3
update: null
